'use strict';

var errorStatus = {
    ACCESS_TOKEN_EXPIRED:  'ACCESS_TOKEN_EXPIRED',
    DATA_NOT_FOUND: 'DATA_NOT_FOUND',
    EMAIL_EXISTS: 'EMAIL_EXISTS',
    INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
    INTERNAL_DB_ERROR: 'INTERNAL_DB_ERROR',
    INVALID_EMAIL: 'INVALID_EMAIL',
    INVALID_PARAMETER: 'INVALID_PARAMETER',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    PERMISSION_DENIED: 'PERMISSION_DENIED'
};

var ACCESS_TOKEN_EXPIRED =  new Error('Access token has expired');
var DATA_NOT_FOUND  = new Error('Data not found');
var EMAIL_EXISTS = new Error();
var INVALID_ACCESS_TOKEN = new Error('Invalid access token');
var INTERNAL_DB_ERROR = new Error('Internal database error');
var INVALID_EMAIL = new Error('Invalid email address');
var INVALID_PARAMETER = new Error('Invalid parameter');
var INVALID_PASSWORD = new Error('Invalid password');
var INTERNAL_SERVER_ERROR = new Error('Internal server error');
var PERMISSION_DENIED = new Error('Permission denied');

ACCESS_TOKEN_EXPIRED.code   = 400;
DATA_NOT_FOUND.code         = 404;
EMAIL_EXISTS.code           = 400;
INVALID_ACCESS_TOKEN.code   = 400;
INTERNAL_DB_ERROR.code      = 500;
INVALID_EMAIL.code          = 400;
INVALID_PARAMETER.code      = 400;
INVALID_PASSWORD.code       = 400;
INTERNAL_SERVER_ERROR.code  = 500;
PERMISSION_DENIED.code      = 401;

module.exports = {
    ACCESS_TOKEN_EXPIRED:  ACCESS_TOKEN_EXPIRED,
    DATA_NOT_FOUND: DATA_NOT_FOUND,
    EMAIL_EXISTS: EMAIL_EXISTS,
    INVALID_ACCESS_TOKEN: INVALID_ACCESS_TOKEN,
    INTERNAL_DB_ERROR: INTERNAL_DB_ERROR,
    INVALID_EMAIL: INVALID_EMAIL,
    INVALID_PARAMETER: INVALID_PARAMETER,
    INVALID_PASSWORD: INVALID_PASSWORD,
    INTERNAL_SERVER_ERROR: INTERNAL_SERVER_ERROR,
    PERMISSION_DENIED: PERMISSION_DENIED,

    errorStatus: errorStatus
};